// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfl-JoLTY7LYF9pjDxpo9dZ-JkLDIhW1Y',
    appId: '1:857343104884:android:826f1df7e379c71daafe21',
    messagingSenderId: '857343104884',
    projectId: 'evently-235f3',
    storageBucket: 'evently-235f3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6m2INbHf-OLhOVWKuYzL6sEyDOThmOQ',
    appId: '1:857343104884:ios:df52468d6238512caafe21',
    messagingSenderId: '857343104884',
    projectId: 'evently-235f3',
    storageBucket: 'evently-235f3.firebasestorage.app',
    iosClientId: '857343104884-2gefda9ie59ehhjnev20l527lfllvdon.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRS5gWRhZbJHsNf-bVKDREtjzhz9ZRDGU',
    appId: '1:857343104884:web:956c7dfc78184cc3aafe21',
    messagingSenderId: '857343104884',
    projectId: 'evently-235f3',
    authDomain: 'evently-235f3.firebaseapp.com',
    storageBucket: 'evently-235f3.firebasestorage.app',
    measurementId: 'G-EZN16Q9ZR8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6m2INbHf-OLhOVWKuYzL6sEyDOThmOQ',
    appId: '1:857343104884:ios:df52468d6238512caafe21',
    messagingSenderId: '857343104884',
    projectId: 'evently-235f3',
    storageBucket: 'evently-235f3.firebasestorage.app',
    iosClientId: '857343104884-2gefda9ie59ehhjnev20l527lfllvdon.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRS5gWRhZbJHsNf-bVKDREtjzhz9ZRDGU',
    appId: '1:857343104884:web:aca3c8a0addae982aafe21',
    messagingSenderId: '857343104884',
    projectId: 'evently-235f3',
    authDomain: 'evently-235f3.firebaseapp.com',
    storageBucket: 'evently-235f3.firebasestorage.app',
    measurementId: 'G-RZ8D0MQ1XZ',
  );
}
